route:
    group_by: [Alertname]
    group_interval: 30s
    repeat_interval: 30s
    # Send all notifications to me.
    receiver: email-me
receivers:
- name: email-me
  email_configs:
  - send_resolved: true
    to: address@gmail.com
    from: address@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "address@gmail.com"
    auth_identity: "address@gmail.com"
    auth_password: "****"
